# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default='', max_length=128, verbose_name='文章简介'),
            preserve_default=False,
        ),
    ]
