# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.TextField(max_length=24, unique=True, verbose_name='标题'),
        ),
    ]
