# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190717_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(max_length=128, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=24, unique=True, verbose_name='标题'),
        ),
    ]
