# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190717_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='articles', verbose_name='特色图片'),
            preserve_default=False,
        ),
    ]
